### ISSUE TITLE
Add storage switch filter for filtering PVCs

### ISSUE THREAD

**Issue by sagarkrsd** [mayadata-io/scope#4]
## FEATURE REQUEST
1. **What feature/change ?**
Add a storage switch filter having value storage on/storage off in order to filter all PVCs among all the resources present in a particular category such as Pod, Controller, Services, etc.
Whenever storage filter is switched on, it will filter out all the PVCs among all the resources present inside a particular category.
2. **Why ?**
The storage filter is needed in order to filter only the PVC resources present among a large no of resources.
3. **Why NOT ?**

4. **Any possible external/internal feature-break ?**

**Comment by ibreakthecloud** [comment]
fixes: #6
