### ISSUE TITLE
Write unit-test cases for new/modified methods in scope/report/id.go.

### ISSUE THREAD

**Issue by avishnu** [mayadata-io/scope#78]
FEATURE REQUEST:

- Write unit-test cases for the methods that are newly added or modified in the file: scope/report/id.go.
- The test-cases have to be written in scope/report/id_test.go.
- Ensure that the test cases are not too complicated. Follow the guidelines https://github.com/openebs/openebs/blob/master/contribute/CONTRIBUTING-TO-DEVELOPER-DOC.md

**Comment by akhilerm** [comment]
I would like to take up and work on this issue. Can someone guide me?

**Comment by satyamz** [comment]
Covered in #86
